version: '3.3'

networks:
  web:
    external: true

services:
  tooling:
    container_name: chgloe_tooling
    build:
      context: .
      dockerfile: ./docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - web
    tty: true
    working_dir: /var/www/html
    ports:
      - "8787:8080"
      - "8587:5000"
    volumes:
      - ./:/var/www/html:delegated
    restart: always
